---
title: "Praktikum Komstat Pertemuan 10"
author: "Alwan Rahmana"
date: "5/11/2022"
output: word_document
---

```{r}

library("moments")
install.packages("normtest")
install.packages("nortest")
```

```{r}
data_menceng_kanan<-c(12,14,15,16,13,14,17,18,25,26,23,27,40,22,42,12,12,73,73,84,85)
data_menceng_kiri<-c(12,24,35,36,43,54,67,78,85,93,87,90,92,90,92,82,73,83,84,95,96)


stem(data_menceng_kanan)
simetris<-c(10,20,30,30,30,40,40,40,50,50,50,50,50,50,50,70,70,70,80,80,80,90,100)
stem(simetris)
par(mfrow=c(1,3))

#Positive skew 
hist(data_menceng_kanan,main="Positive Skew") 

#Negative skew 
hist(data_menceng_kiri,main="Negative Skew") 

#Symetrical hist
hist(simetris,main="Symetrical Skew")
```

```{r}
shapiro.test(data_menceng_kiri)
shapiro.test(data_menceng_kanan)
shapiro.test(simetris)
```


```{r}
library(normtest) 
library(nortest)

lillie.test(data_menceng_kiri)
lillie.test(data_menceng_kanan)
lillie.test(simetris)
```
```{r}
chisq.test(data_menceng_kanan)
chisq.test(data_menceng_kiri)
chisq.test(simetris)
```

```{r}
```


```{r}
prop.test(x=c(9,13),n=c(20,15),alternative="two.sided")
```

```{r}
crosstab<-matrix(c(40,30,20,35),ncol=2)
crosstab
#colnames(crosstab)<-c("")
chisq.test(crosstab)
```

